#!/bin/bash
#This script searches all the dataset dir within the data_dir
#Load the edge and vertices within
data_dir=$HOME/graph_data/jesun
declare -a prg=("sssp_data_thread_centric" "sssp_data_warp_centric" "sssp_topo_thread_centric" "sssp_topo_warp_centric")

timestamp=$(date +"%Y%m%d%H%M%S")

for prog in "${prg[@]}"
do
    log=gpu_${prog}_${timestamp}.csv
    touch $log
    echo "data,h2dtime,d2htime,kerneltime,time" > $log
    for data in "$data_dir"/*
    do
       dataname=${data##*/}
       echo -n "${dataname}," >> $log
       ./$prog \
       --root 999 \
       --dataset $data \
       >> $log ;
    done
done
