#!/bin/bash
#This script searches all the dataset dir within the data_dir
#Load the edge and vertices within
data_dir=$HOME/graph_data/friendster

function usage
{
    echo "usage: run [gcc/icc] [csv/csr] [program]"
}
if [ -z "$1" ]
  then
    usage
    exit
fi

if [ -z "$2" ]
  then
    usage
    exit
fi

if [ -z "$3" ]
  then
    usage
    exit
fi
timestamp=$(date +"%Y%m%d%H%M%S")


log=$3_$1_$2_$timestamp.csv
touch $log
for data in "$data_dir"/*
do
  dataname=${data##*/}
  echo "threadnum,loadingtime,time,$dataname" >> $log
  for var in 1 2 4 8 16 32 64 128 256 512
  do
  ./$3 --threadnum $var\
  --dataset $data \
  >> $log ;
  done
done

