#!/bin/bash
#This script searches all the dataset dir within the data_dir
#Load the edge and vertices within
data_dir=$HOME/graph_data/friendster
declare -a prg=("degree_centr")
 
timestamp=$(date +"%Y%m%d%H%M%S")

for prog in "${prg[@]}"
do
    log=gpu_$prog_$timestamp.csv
    touch $log
    echo -n "h2dtime,d2htime,kerneltime,time" > $log
    for data in "$data_dir"/*
    do
       dataname=${data##*/}
       echo ",$dataname" >> $log
       ./$prog \
       --dataset $data \
       >> $log ;
    done
done
