#!/bin/bash
#This script searches all the dataset dir within the data_dir
#Load the edge and vertices within
data_dir=$HOME/graph_data/friendster
declare -a prg=("kcore")
 
for prog in "${prg[@]}"
do
    rm -rf log$prog
    mkdir -p log$prog
    for data in "$data_dir"/*
    do
       sub=${data##*/}
       touch log$prog/$sub.csv
       echo "loadingtime,h2dtime,d2htime,kerneltime,time" > log$prog/$sub.csv
       ./$prog \
       --dataset $data \
       >> log$prog/$sub.csv ;
    done
done


tar czf kc_gpu.tar.gz log*
